### ISSUE TITLE
Why set learnable parameters in function GAP

### ISSUE THREAD

**Issue by dbzqyyy** [c-yn/SFNet#1]
Hi, I observed that setting the parameter `fscale_d` and `fscale_h` in the function and it has the values 0 and 1 respectively, why is this? Will this ensure that the gradient propagates properly?

**Comment by c-yn** [comment]
Hi, thanks for the question.

We just want the network to learn more high-frequency signals by setting 1 for fscale_h.

You could try to set the same value for both fscale_d/h.

Thanks.
