### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by peylnog** [c-yn/SFNet#2]
I tried to run python3 main.py in motion deblur, but I had the following problem [at this](https://github.com/c-yn/SFNet/blob/c8d241ecaa9e9ac568375292979bbeae1a8313f3/Motion_deblurring/models/layers.py#L137
)

ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 72, 1, 1])

This error seems to be because, in the training phase, batchnorm receives input tensor ( bxcx1x1 ).

I would appreciate it if you could tell me how to debug or update the repo

**Comment by stacyyy214** [comment]
> [我尝试在运动去模糊中运行 python3 main.py，但此时](https://github.com/c-yn/SFNet/blob/c8d241ecaa9e9ac568375292979bbeae1a8313f3/Motion_deblurring/models/layers.py#L137)遇到了以下问题[](https://github.com/c-yn/SFNet/blob/c8d241ecaa9e9ac568375292979bbeae1a8313f3/Motion_deblurring/models/layers.py#L137)
> 
> ValueError：训练时每个通道预期有超过 1 个值，输入大小为 torch.Size([1, 72, 1, 1])
> 
> 这个错误似乎是因为在训练阶段，batchnorm 接收输入张量（bxcx1x1）。
> 
> 如果你能告诉我如何调试或更新 repo，我将不胜感激

我也遇到这个问题，请问你是怎么解决的呢？

**Comment by zhengyuxuan614** [comment]
> I tried to run python3 main.py in motion deblur, but I had the following problem [at this](https://github.com/c-yn/SFNet/blob/c8d241ecaa9e9ac568375292979bbeae1a8313f3/Motion_deblurring/models/layers.py#L137)
> 
> ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 72, 1, 1])
> 
> This error seems to be because, in the training phase, batchnorm receives input tensor ( bxcx1x1 ).
> 
> I would appreciate it if you could tell me how to debug or update the repo

I've encountered this issue too. How did you solve it?

**Comment by 17866520451** [comment]
model.eval()  try again
