### ISSUE TITLE
The experiment results using the publicly available weights are inconsistent.

### ISSUE THREAD

**Issue by aoe-wyb** [c-yn/SFNet#5]
Why can't I achieve the PSNR of 40.05 in SOTS-Outdoor test results using the pre-trained weights you provided in your paper? Thanks.
![image](https://github.com/c-yn/SFNet/assets/62412181/bf3aad63-f1bb-4cf8-938e-7803d7af4bfc)
![image](https://github.com/c-yn/SFNet/assets/62412181/386b6b93-5794-4b0f-b36b-a6ac79b6c99d)

**Comment by c-yn** [comment]
Hi,

Thanks for your email and question.

We have double-checked our results for SOTS-Outdoor on different GPUs (NVIDIA A40 and V100) and got the same score as reported in our paper (40.05 dB PSNR).

We have replied  your email with the testing logs and environment settings for both devices.
