### ISSUE TITLE
Is it correct to test with TLC?

### ISSUE THREAD

**Issue by FireWallDragonDarkFluid** [c-yn/SFNet#7]
Hi!

Thanks for sharing the code.
I was wondering, it seems that you have conducted experiments and recorded scores base on TLC.

Is that a right thing to do? Since TLC definitely will improve model's performance, in that case, there's
no way to identify whether it's TLC that made the network outperform others or it's the method proposed
in the paper.

**Comment by c-yn** [comment]
Hi, thanks for your questions.

We can identify the performance improvement of our method by simply removing TLC during training and testing, i.e., using plain average pooling.
