### ISSUE TITLE
pre-trained model on RSBlur

### ISSUE THREAD

**Issue by thqiu0419** [c-yn/SFNet#8]
Thx  for your awesome code!
Could you please open source the pre-trained model on RSBlur so we can compare it~
thanks again~

**Comment by c-yn** [comment]
Hi, you can directly download our results on RSBlur from the link in the section of Results of this repo for more convenience.

**Comment by thqiu0419** [comment]
Thanks, but we would like to generalize the validation using the pre-trained model of RSBlur, so could you please let me get this pre-trained model if it is convenient for you?

**Comment by c-yn** [comment]
Hi, we have uploaded the model in the link and updated the code.

**Comment by thqiu0419** [comment]
Thank you very much, that's very helpful~
